//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terelelli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCompletionTimes
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
