//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terelelli.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.TaskCompletionTimes = new HashSet<TaskCompletionTimes>();
            this.TaskCompletionTimes1 = new HashSet<TaskCompletionTimes>();
        }
    
        public int TaskId { get; set; }
        public Nullable<int> PanelId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public string TaskDescription { get; set; }
        public string TaskNotes { get; set; }
        public Nullable<System.DateTime> TaskFinishDate { get; set; }
        public Nullable<long> TaskEstimatedDuration { get; set; }
    
        public virtual Panels Panels { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskCompletionTimes> TaskCompletionTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskCompletionTimes> TaskCompletionTimes1 { get; set; }
    }
}
